export const productsArray = [
  {
    id: 1,
    name: 'iPhone 13 Pro',
    description: 'This is iPhone 13 Pro',
    capacity: '128',
    type: 'phone',
    price: '1100',
  },
  {
    id: 2,
    name: 'iPhone 12 Pro',
    description: 'This is iPhone 12 Pro',
    capacity: '128',
    type: 'phone',
    price: '2000',
  },
  {
    id: 3,
    name: 'iPhone 13 Pro',
    description: 'This is iPhone 13 Pro',
    capacity: '256',
    type: 'phone',
    price: '2500',
  },
  {
    id: 4,
    name: 'iPhone 11 Pro',
    description: 'This is iPhone 11 Pro',
    capacity: '64',
    type: 'phone',
    price: '1500',
  },
  {
    id: 5,
    name: 'iPhone X Pro',
    description: 'This is iPhone X Pro',
    capacity: "128",
    type: 'phone',
    price: '1600',
  },
  {
    id: 6,
    name: 'iPhone X Pro',
    description: 'This is iPhone X Pro',
    capacity: '256',
    type: 'phone',
    price: '500',
  },
]